services:
  tenant-api:
    build:
      context: .
      dockerfile: ./apps/tenant-api/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - shared
    depends_on:
      - postgres-db

  backend-api:
    build:
      context: .
      dockerfile: ./apps/backend-api/Dockerfile
    restart: always
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:postgres@postgres-db:5432
      - ADMIN_EMAIL=admin@localhost.com
      - ADMIN_PASSWORD=admin123
      - JWT_SECRET=secret
    ports:
      - 3001:3001
    networks:
      - shared
    depends_on:
      - postgres-db

  postgres-db:
    hostname: postgres-db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - shared
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  shared:
    name: shared

volumes:
  postgres-db-data:
